version: '3.3'
services:
  systemb:
    build: .
    ports:
      - 82:80
  db-b:
    image : mysql
    build: .
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    networks:
      b-net:
networks:
  b-net:

